project:
  type: book
  output-dir: docs
  resources:
    - service-worker.js
    - pwa/manifest.webmanifest
    - pwa/offline.html
    - pwa/icons/*

# execute:
#   engine: jupyter

# jupyter: mas2901

book:
  title: "MAS2901: Statistical Inference"
  author: "Matthew Fisher"
  date: ""
  chapters:
    - index.qmd
    - part: "Part I — Foundations"
      chapters:
        - 1-prob-theory.qmd
        - 2-what-is-stats-inference.qmd
        - 3-types-of-inference.qmd
    - part: "Part II — Parameter Estimation"
      chapters:
        - 4-freq-point-estimation.qmd
        - 5-likelihood.qmd
        - 6-bayes-inference.qmd
    - part: "Part III - Interval Estimation"
      chapters:
        - 7-freq-interval-estimation.qmd
        - 8-bayes-interval-estimation.qmd
    - part: "Part IV — Hypothesis Testing"
      chapters:
        - 9-freq-hypothesis-testing.qmd
        - 10-bayes-hypothesis-testing.qmd
    - part: "Additional Material"
      chapters:
        - app-formula-sheet.qmd
        - app-revision-sheet.qmd
        - app-distribution-explorer.qmd
        - app-question-bank.qmd
  sidebar:
    style: floating
    search: true
  navbar: 
    title: ""
    logo: images/ncl_logo_light.png
    search: false
  search:
    location: sidebar
    type: textbox
    keyboard-shortcut: "F"

# bibliography: references.bib

math: 
  renderer: mathjax   # should try "katex" for faster rendering if all features work

brand: theming/_brand.yml
format:
  html:
    echo: false
    theme:
      light: light_theme.scss
      dark: dark_theme.scss

    filters:
      - callouty-theorem
    css: 
      - theming/math-scroll.css
      - theming/callout-style.css
      - theming/floating-code.css
      - theming/font.css
      - theming/no-xref-suffix.css
      - theming/scrollbar.css
      - theming/nav-tabs.css
      - theming/header.css
      - theming/question-bank.css
      - theming/sidebar.css
      - theming/lecture-zoom.css
    include-after-body:
      - theming/no-xref-suffix.html
      - theming/close-codefold.html
      - theming/header.html
      - theming/callout-prefix-removal.html
      - theming/zoom-button.html
    include-in-header: 
      # - theming/favicons.html
      - pwa/pwa-head.html


  # pdf:
  #   documentclass: scrreprt
  #   include-in-header:
  #     text: |
  #       \usepackage{newunicodechar}
  #       \usepackage{emoji}
  #       \newunicodechar{✨}{\emoji{sparkles}}
  #       \usepackage{amsthm}
  #       \usepackage{mathtools} 
  #       \usepackage{hyperref}
  #       \usepackage{cleveref}
  #       \makeatletter
  #       \newenvironment{refproof}[1][]%
  #         {\if\relax\detokenize{#1}\relax
  #            \begin{proof}
  #          \else
  #            % With cleveref:
  #            %\begin{proof}[Proof of \cref{#1}]
  #            % Without cleveref:
  #            \begin{proof}[Proof of \ref{#1}]
  #          \fi}%
  #         {\end{proof}}
  #       \makeatother


callouty-theorem:
  thm:
    override-title: false # do not override the title of the callout (title won't show when `appearance` set to `simple` or `minimal`)
    callout: # parameters of the wrapping callout. see Quarto documentation of callouts for more details
      type: note
      appearance: minimal
  prp:
    override-title: false
    callout:
      type: note
      appearance: minimal
  exr:
    override-title: false
    callout:
      type: tip
      appearance: minimal
  proof: # also support wrapping proof-like environments
    override-title: true # override the title of the callout by the name of the theorem
    callout:
      type: note
      appearance: default
      collapse: true
      icon: true
  solution:
    override-title: true
    callout:
      type: tip
      appearance: default
      collapse: true
      icon: true
  remark:
    override-title: true
    callout:
      type: tip
      appearance: default
      collapse: true
      icon: true
  exm:
    override-title: false
    callout:
      type: caution
      appearance: minimal
      collapse: false

  # theorems types not specified in the metadata will be rendered as is
  cor: default # calloutify corollaries with default style
  def:
    override-title: false
    callout:  # also support default style here
      appearance: minimal
      type: note
      collapse: false

editor:
  render-on-save: true

